apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: deployment-event-platform
  namespace: argocd
spec:
  description: Deployment Event Platform project
  sourceRepos:
    - '*'
  destinations:
    - namespace: deployment-event-platform
      server: https://kubernetes.default.svc
    - namespace: istio-system
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: deployment-event-platform
      server: https://kubernetes.default.svc
    - namespace: arc-systems
      server: https://kubernetes.default.svc
    - namespace: arc-runner
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
